working_directory: '<WORKING DIRECTORY>'
threads: 8
subsampling:
  samples:
    PGXXOX240045:
      name: 'Myeloid_Female'
      path: '<BAM PATH>'
      weight: 15
      n_reads: 14415795
    PGXXOX240047:
      name: 'B_Cell_Female'
      path: '<BAM PATH>'
      weight: 10
      n_reads: 10066037
    PGXXOX240048:
      name: 'CD4_Female'
      path: '<BAM PATH>'
      weight: 0
      n_reads: 13196103
    PGXXOX240049:
      name: 'CD8_Female'
      path: '<BAM PATH>'
      weight: 25
      n_reads: 13118764
    PGXXOX240050:
      name: 'Neutrophill_2'
      path: '<BAM PATH>'
      weight: 0
      n_reads: 8781207
    PGXXOX240051:
      name: 'NK_Female'
      path: '<BAM PATH>'
      weight: 15
      n_reads: 9912801

  total_reads: 20000000
illumina_mapping_file: '<Path>'
methatlas_path: '<METHATLAS Path>'
blocks_file: '<PATH>'
